### PR TITLE
Focus "Home" tab by default

### PR DESCRIPTION
**Pull request by maginporia**
Currently, the Home tab does not have focus after launch.

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
My intention was to focus the content of the home tab by default but I couldn't get that working.

https://github.com/nielsvanvelzen/tv-launcher/blob/6927139c57ebc7534147619851285deee63d911e/app/src/main/kotlin/nl/ndat/tvlauncher/ui/screen/launcher/LauncherScreen.kt#L31-L32

Perhaps we can use the same method that you've used here to get that working, by adding a LaunchedEffect instead of a focusRestorer.

**Comment by maginporia** [comment]
I see. I just pushed some new changes.
Please take a look.

**Comment by nielsvanvelzen** [comment]
With the latest changes I'm seeing some weird behavior when I move focus to the toolbar and then back to the content. I would expect the app card that was previously focused to be focused again but I don't see any visual indicator.

[9980000421.webm](https://github.com/user-attachments/assets/97b13f1f-00e2-4b48-9866-f5f5aed489cf)

**Comment by maginporia** [comment]
Fixed, I didn’t notice that there was already a `focusRestorer`.

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
I made some final adjustments during testing but everything is working now! thanks for the pull request 😄

**Pull request merged**
